export const PERMISSIONS = [
  'company.read',
  'company.update',
  'user.manage',
  'kyb.submit',
  'kyb.read',
  'kyb.review',
  'beneficiary.create',
  'beneficiary.read',
  'beneficiary.update',
  'quote.create',
  'quote.read',
  'payment.create',
  'payment.read',
  'payment.approve',
  'payment.cancel',
  'compliance.read',
  'compliance.review',
  'ledger.read',
  'wallet.topup',
  'webhook.read',
  'reconciliation.read',
  'reconciliation.run',
  'audit.read',
  'platform.admin',
] as const;
export type Permission = (typeof PERMISSIONS)[number];

export const ROLES = ['PLATFORM_ADMIN', 'COMPANY_ADMIN', 'MAKER', 'APPROVER', 'VIEWER'] as const;
export type RoleName = (typeof ROLES)[number];
export const COMPANY_ROLES: readonly RoleName[] = ['COMPANY_ADMIN', 'MAKER', 'APPROVER', 'VIEWER'];

/** docs/PRD.md §5 — the permission matrix. A test asserts the database matches this exactly. */
export const ROLE_PERMISSIONS: Record<RoleName, readonly Permission[]> = {
  PLATFORM_ADMIN: [
    'platform.admin',
    'company.read',
    'kyb.read',
    'kyb.review',
    'beneficiary.read',
    'quote.read',
    'payment.read',
    'compliance.read',
    'compliance.review',
    'ledger.read',
    'webhook.read',
    'reconciliation.read',
    'reconciliation.run',
    'audit.read',
  ],
  COMPANY_ADMIN: [
    'company.read',
    'company.update',
    'user.manage',
    'kyb.submit',
    'kyb.read',
    'beneficiary.create',
    'beneficiary.read',
    'beneficiary.update',
    'quote.create',
    'quote.read',
    'payment.create',
    'payment.read',
    'payment.approve',
    'payment.cancel',
    'compliance.read',
    'ledger.read',
    'wallet.topup',
    'audit.read',
  ],
  MAKER: [
    'company.read',
    'kyb.read',
    'beneficiary.create',
    'beneficiary.read',
    'beneficiary.update',
    'quote.create',
    'quote.read',
    'payment.create',
    'payment.read',
    'payment.cancel',
    'compliance.read',
  ],
  APPROVER: [
    'company.read',
    'kyb.read',
    'beneficiary.read',
    'quote.read',
    'payment.read',
    'payment.approve',
    'compliance.read',
    'ledger.read',
  ],
  VIEWER: ['company.read', 'kyb.read', 'beneficiary.read', 'quote.read', 'payment.read', 'ledger.read'],
};

export const ROLE_SCOPE: Record<RoleName, 'PLATFORM' | 'COMPANY'> = {
  PLATFORM_ADMIN: 'PLATFORM',
  COMPANY_ADMIN: 'COMPANY',
  MAKER: 'COMPANY',
  APPROVER: 'COMPANY',
  VIEWER: 'COMPANY',
};
